---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyr)
set.seed(1)
setwd("/Users/LL/Documents/HKUST/KDD/R code")

train_model = read.csv("train_model.csv")
train_model[!complete.cases(train_model),] %>% distinct(start_date) # days where weather data is incomplete
train_model = train_model[complete.cases(train_model),] %>% select(-start_date, -start_hour) # remove NAs

# train_model = train_model %>% mutate(link_id = as.factor(link_id)) 
# don't use for xgboost otherwise can't build xgb.DMatrix

# as.matrix converts the num/int/chr/factor typing so this is only used for xgboost input
X_train = train_model %>% select(-mean_travel_time) %>% as.matrix()
y_train = train_model$mean_travel_time
```
# Construct test_model and X_test
```{r}
# Construct the X_test matrix

# functions from Preprocessing.R
join_weather <- function(links, weather) {
  links = mutate(links, weather_group = 3*(start_hour%/%3))
  weather = mutate(weather, date = as.Date(date))
  links = left_join(links, weather, by = c("start_date" = "date", "weather_group" = "hour"))
  links = select(links, -weather_group)
  return(links)
}
join_link_information <- function(links, link_information) {
  link_information = link_information %>% select(link_id, length, width)
  links = left_join(links, link_information, by = c("link_id" = "link_id"))
  return(links)
}
convert_weekday <- function(char_weekday) {
  if (char_weekday == "Monday") {
    return(1)
  } else if (char_weekday == "Tuesday") {
    return(2)
  } else if (char_weekday == "Wednesday") {
    return(3)
  } else if (char_weekday == "Thursday") {
    return(4)
  } else if (char_weekday == "Friday") {
    return(5)
  } else if (char_weekday == "Saturday") {
    return(6)
  } else {
    return(7)
  }
}

test_weather <- read.csv("weather (table 7)_test1.csv")
test_model = read.csv("submission_sample_travelTime.csv") %>% select(-avg_travel_time) # take out sample travel time

create_links <- function(intersection_id, tollgate_id) {
  chosen_path = paste(intersection_id, tollgate_id, sep = "")
  if (chosen_path == "C1") {
    path_links = "115, 102, 109, 104, 112, 111, 103, 116, 101, 121, 106, 113"
  } else if (chosen_path == "C3") {
    path_links = "115, 102, 109, 104, 112, 111, 103, 122"
  } else if (chosen_path == "B1") {
    path_links = "105, 100, 111, 103, 116, 101, 121, 106, 113"
  } else if (chosen_path == "B3") {
    path_links = "105, 100, 111, 103, 122"
  } else if (chosen_path == "A3") {
    path_links = "110, 123, 107, 108, 119, 114, 118, 122"
  } else if (chosen_path == "A2") {
    path_links = "110, 123, 107, 108, 120, 117"
  } 
  return(path_links)
}

test_model =
  test_model %>% separate(time_window, into = c("temp", "start_date"), sep = '\\[', remove = FALSE) %>% 
  separate(start_date, into = c("start_date", "end_date"), sep = ',') %>%
  separate(start_date, into = c("start_date", "start_time"), sep = ' ') %>%
  separate(start_time, into = c("start_hour", "start_minute", "start_second"), sep = ':') %>%
  mutate(start_date = as.Date(start_date), start_hour = as.numeric(start_hour), start_minute = as.numeric(start_minute)) %>%
  mutate(day_time_group = 1 + start_hour*3 + start_minute%/%20 ) %>%
  join_weather(test_weather) %>%
  select(-temp, -end_date, -start_second) %>%
  mutate(path = paste(intersection_id, tollgate_id, sep = "")) %>%
  mutate(links = mapply(create_links, intersection_id, tollgate_id))

create_subset <- function(test_model, intersection, tollgate) {
  chosen_path = paste(intersection, tollgate, sep = "")
  if (chosen_path == "C1") {
    path_length = 12
  } else if (chosen_path == "C3") {
    path_length = 8
  } else if (chosen_path == "B1") {
    path_length = 9
  } else if (chosen_path == "B3") {
    path_length = 5
  } else if (chosen_path == "A3") {
    path_length = 8
  } else if (chosen_path == "A2") {
    path_length = 6
  }
  sequence_list = c()
  for (i in 1:path_length) {
    sequence_list = c(sequence_list, paste("sequence_", i, sep = ""))
  }
  test_model = test_model %>% filter(intersection_id == intersection, tollgate_id == tollgate) %>%
    separate(links, into = sequence_list, sep = ",")
  test_model = test_model %>% gather(sequence, link_id, (ncol(test_model)-path_length+1):ncol(test_model))
}

subsetA2 = create_subset(test_model, intersection = "A", tollgate = 2)
subsetA3 = create_subset(test_model, intersection = "A", tollgate = 3)
subsetB1 = create_subset(test_model, intersection = "B", tollgate = 1)
subsetB3 = create_subset(test_model, intersection = "B", tollgate = 3)
subsetC1 = create_subset(test_model, intersection = "C", tollgate = 1)
subsetC3 = create_subset(test_model, intersection = "C", tollgate = 3)

table3 <- read.csv("links (table 3).csv")

test_model = rbind(subsetA2, subsetA3, subsetB1, subsetB3, subsetC1, subsetC3) %>% 
  select(-start_hour, -start_minute, -path, -sequence) %>%
  mutate(link_id = as.numeric(link_id)) %>%
  join_link_information(table3) %>%
  mutate(weekday = weekdays(start_date)) %>%
  mutate(weekday = as.numeric(sapply(weekday, convert_weekday)))

write.csv(test_model, file = "test_model.csv", row.names = FALSE)
```